# This fragment contains config for MPTCP+detour
CONFIG_MPTCP=y
CONFIG_MPTCP_PM_ADVANCED=y
CONFIG_MPTCP_DETOUR=y
CONFIG_DEFAULT_DETOUR=y
CONFIG_DEFAULT_MPTCP_PM="detour"
CONFIG_MPTCP_SCHED_ADVANCED=y
CONFIG_MPTCP_ROUNDROBIN=y
CONFIG_MPTCP_REDUNDANT=y
CONFIG_DEFAULT_MPTCP_SCHED="default"

CONFIG_IP_MULTIPLE_TABLES=y
CONFIG_IPV6=y

# Need to have sysctl too
CONFIG_PROC_SYSCTL=y

# DHCPCD requires epoll and unix sockets
CONFIG_EPOLL=y
CONFIG_UNIX=y
CONFIG_FILE_LOCKING=y

# tun devices for using openvpn
CONFIG_TUN=y

# additional congestion control options for experimentation
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_LIA=y
CONFIG_TCP_CONG_OLIA=y
CONFIG_TCP_CONG_WVEGAS=y
CONFIG_TCP_CONG_BALIA=y
