# This fragment contains config for MPTCP+detour
CONFIG_MPTCP=y
CONFIG_MPTCP_PM_ADVANCED=y
CONFIG_MPTCP_DETOUR=y
CONFIG_DEFAULT_DETOUR=y
CONFIG_DEFAULT_MPTCP_PM="detour"
CONFIG_MPTCP_SCHED_ADVANCED=y
CONFIG_DEFAULT_MPTCP_SCHED="default"

CONFIG_IP_MULTIPLE_TABLES=y

# Need to have sysctl too
CONFIG_PROC_SYSCTL=y
